package dao;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;

import beans.User;

public class UserDAO {
	private Connection connection;
	
	public UserDAO(Connection connection) {
		this.connection = connection;
	}
	
	//insert of a new user
	public User insertUser(String username, String password) throws SQLException {
		User user = null;
		String query = "INSERT INTO dbtiwexam1920js.user(username, password) VALUES (?, ?)";
		PreparedStatement pstatement = null;
		if (!isPresent(username)) {
			try {
				pstatement = connection.prepareStatement(query, Statement.RETURN_GENERATED_KEYS);
				pstatement.setString(1, username);
				pstatement.setString(2, password);
				pstatement.executeUpdate();
	
				ResultSet tableKeys = pstatement.getGeneratedKeys();
				tableKeys.next();
				int autoGeneratedID = tableKeys.getInt(1);	//the db set a new autoincremented id for the user
				
				user = new User();
				user.setId(autoGeneratedID);
				user.setUsername(username);
				
			} catch (SQLException e) {
			    e.printStackTrace();
				throw new SQLException(e);
	
			} finally {
				
				try {
					pstatement.close();
				} catch (Exception e2) {
					throw new SQLException(e2);
				}
			}			
		}
		return user;
	}
	
	//authentication of the user
	public User authenticateUser(String username, String password) throws SQLException {
		User user = null;
		String query = "SELECT * FROM dbtiwexam1920js.user WHERE username = ? and password = ?";
		ResultSet result = null;
		PreparedStatement pstatement = null;
		
		try {
			pstatement = connection.prepareStatement(query);
			pstatement.setString(1, username);
			pstatement.setString(2, password);
			result = pstatement.executeQuery();
			while (result.next()) {
				user = new User();
				user.setId(result.getInt("id"));
				user.setUsername(result.getString("username"));
			}
		} catch (SQLException e) {
		    e.printStackTrace();
			throw new SQLException(e);

		} finally {
			try {
				result.close();
			} catch (Exception e1) {
				throw new SQLException(e1);
			}
			try {
				pstatement.close();
			} catch (Exception e2) {
				throw new SQLException(e2);
			}
		}		
		return user;
	}
	
	//check if the username choosen by the user is already used
	public boolean isPresent(String username) throws SQLException {
		int count = 0;
		String query = "SELECT COUNT(*) FROM dbtiwexam1920js.user WHERE username = ?";
		ResultSet result = null;
		PreparedStatement pstatement = null;
		
		try {
			pstatement = connection.prepareStatement(query);
			pstatement.setString(1, username);
			result = pstatement.executeQuery();
			while (result.next()) {
				count = result.getInt(1);
			}
		} catch (SQLException e) {
		    e.printStackTrace();
			throw new SQLException(e);

		} finally {
			try {
				result.close();
			} catch (Exception e1) {
				throw new SQLException(e1);
			}
			try {
				pstatement.close();
			} catch (Exception e2) {
				throw new SQLException(e2);
			}
		}	
		if (count==0)	//if count is 0 the username isn't present
			return false;
		else			
			return true;
	}
	
}
